### ISSUE TITLE
`Send` is not implemented for `*mut fdk_aac_sys::AACENCODER`

### ISSUE THREAD

**Issue by harlanc** [haileys/fdk-aac-rs#9]
The following error happens when I use aac encoder in tokio thread：
    
     within `[async block@protocol/webrtc/src/whip.rs:131:22: 237:10]`, the trait `Send` is not implemented for `*mut fdk_aac_sys::AACENCODER`

Add the following two lines in enc.rs can fix the problem:

    unsafe impl Send for Encoder {}
    unsafe impl Sync for Encoder {}

I'm not sure if this is appropriate.

**Comment by harlanc** [comment]
I did some tests for the above update, and it seems good, so could you make a new crate version for this? or I can make a new one myself..

**Comment by haileys** [comment]
Released [`v0.6.0`](https://github.com/haileys/fdk-aac-rs/tree/v0.6.0) addings impls for Send and Sync on `EncoderHandle`
